/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * var.js — Fallback data per template
 * Digunakan sebagai default ketika API tidak tersedia.
 * Struktur setiap template bisa jadi berbeda-beda.
 */

var FALLBACK = {
    "brown-casual": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        fatherGroom: "Andi Idris Sulaiman",
        fatherBride: "Syam Haeruddin",
        akadDatetime: "2026-12-12T10:00:00+07:00",
        akadVenue: "Gedung Serbaguna \"Balai Santika\"",
        akadAddress: "Gedung Serbaguna \"Balai Santika\"",
        akadMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        receptionDatetime: "2026-12-13T12:00:00+07:00",
        receptionVenue: "Gedung Serbaguna \"Balai Santika\"",
        receptionAddress: "Gedung Serbaguna \"Balai Santika\"",
        receptionMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        groomPhoto: "/brown-casual/_assets/img/spouse/new/man.png",
        bridePhoto: "/brown-casual/_assets/img/spouse/new/woman.png",
        backgroundCover: "/brown-casual/_assets/img/bg/bg-2.webp",
        isShowGallery: true,
        isShowStory: true,
        gallery: [
            "/brown-casual/_assets/img/gallery/1.jpg",
            "/brown-casual/_assets/img/gallery/2.jpg",
            "/brown-casual/_assets/img/gallery/3.jpg",
            "/brown-casual/_assets/img/gallery/4.jpg",
            "/brown-casual/_assets/img/gallery/5.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Muh. Fahri Akbar", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Yustisya", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        platform: "Our Platform",
        music: "/music.mp3",
        storyItems: [
            { year: 2015, title: "Kami satu sekolah", description: "Malesuada nibh amet, dui lectus vitae nam malesuada arcu sagittis. Natoque viverra condimentum at condimentum dolor quis aliquam." },
            { year: 2017, title: "Berpisah karena kuliah", description: "Malesuada nibh amet, dui lectus vitae nam malesuada arcu sagittis. Natoque viverra condimentum at condimentum dolor quis aliquam." },
            { year: 2020, title: "Dipertemukan Kembali", description: "Malesuada nibh amet, dui lectus vitae nam malesuada arcu sagittis. Natoque viverra condimentum at condimentum dolor quis aliquam." },
            { year: 2022, title: "Lamaran & Nikah", description: "Malesuada nibh amet, dui lectus vitae nam malesuada arcu sagittis. Natoque viverra condimentum at condimentum dolor quis aliquam." },
        ],
    },

    "green-forest": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        groomPhoto: "/green-forest/_assets/img/spouse/man.jpg",
        bridePhoto: "/green-forest/_assets/img/spouse/woman.jpg",
        backgroundCover: "/green-forest/_assets/img/bg/header.jpg",
        groomRole: "Putra dari",
        brideRole: "Putri dari",
        fatherGroom: "Andi Idris Sulaiman",
        fatherBride: "Syam Haeruddin",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
        quoteSource: "QS. Ar-Rum (30): 21",
        akadDatetime: "2026-12-02T09:00:00+07:00",
        akadVenue: "Gedung Serbaguna",
        akadAddress: "Jl. Lorem Ipsum X No. 123",
        akadMapsUrl: "https://maps.google.com/maps?q=Rootpixel&t=&z=13&ie=UTF8&iwloc=&output=embed",
        receptionDatetime: "2026-12-05T11:00:00+07:00",
        receptionVenue: "Gedung Serbaguna",
        receptionAddress: "Jl. Lorem Ipsum X No. 123",
        receptionMapsUrl: "https://maps.google.com/maps?q=Rootpixel&t=&z=13&ie=UTF8&iwloc=&output=embed",
        isShowGallery: true,
        isShowStory: true,
        gallery: [
            "/green-forest/_assets/img/gallery/1.jpg",
            "/green-forest/_assets/img/gallery/2.jpg",
            "/green-forest/_assets/img/gallery/3.jpg",
            "/green-forest/_assets/img/gallery/4.jpg",
            "/green-forest/_assets/img/gallery/5.jpg",
            "/green-forest/_assets/img/gallery/6.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Muh. Fahri Akbar", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Yustisya", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        platform: "Our Platform",
        music: "/music.mp3",
        section4Img1: "/green-forest/_assets/img/misc/hands-1.jpg",
        section4Img2: "/green-forest/_assets/img/misc/hands-2.jpg",
        storyItems: [
            { title: "Pertemuan keluarga", description: "Libero, sit sit nullam a. Pellentesque auctor vitae est, nisi nulla posuere aliquet.", image: "/green-forest/_assets/img/misc/hands-1.jpg" },
            { title: "Saling mengenal", description: "Libero, sit sit nullam a. Pellentesque auctor vitae est, nisi nulla posuere aliquet.", image: "/green-forest/_assets/img/misc/hands-2.jpg" },
            { title: "Lamaran", description: "Libero, sit sit nullam a. Pellentesque auctor vitae est, nisi nulla posuere aliquet.", image: "/green-forest/_assets/img/misc/room.jpg" },
        ],
    },

    "simple-bless": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        eventDatetime: "2026-12-02T09:00:00+07:00",
        venue: "Jl. Lorem Ipsum X No. 123",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya.",
        openingPhoto: "/simple-bless/_assets/img/gallery/4.jpg",
        closingPhoto: "/simple-bless/_assets/img/gallery/4.jpg",
        storyPhoto1: "/simple-bless/_assets/img/gallery/1.jpg",
        storyPhoto2: "/simple-bless/_assets/img/gallery/2.jpg",
        wishes: [
            { name: "Mumainnah Rusli", message: "Selamat menempuh hidup baru, semoga menjadi keluarga yang sakinah mawaddah warahmah." },
            { name: "Muh. Fahri Akbar", message: "Barakallahu lakuma wa baraka alaikuma wa jama'a bainakuma fi khair." },
            { name: "Yustisya", message: "Semoga langgeng sampai kakek nenek dan selalu bahagia bersama." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
    },

    "simple-beauty": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        eventDatetime: "2026-12-09T13:00:00+08:00",
        venue: "Kediaman Mempelai Wanita, Takalar",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya. - QS. Ar-Rum: 21",
        gallery: [
            "/simple-beauty/_assets/img/gallery/3.jpeg",
            "/simple-beauty/_assets/img/gallery/4.jpg",
            "/simple-beauty/_assets/img/gallery/5.jpeg",
            "/simple-beauty/_assets/img/gallery/7.jpeg",
            "/simple-beauty/_assets/img/gallery/8.jpeg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Selamat menempuh hidup baru, semoga menjadi keluarga yang sakinah mawaddah warahmah." },
            { name: "Muh. Fahri Akbar", message: "Barakallahu lakuma wa baraka alaikuma wa jama'a bainakuma fi khair." },
            { name: "Yustisya", message: "Semoga langgeng sampai kakek nenek dan selalu bahagia bersama." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
    },

    "simple-forest": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        akadDatetime: "2026-12-20T12:00:00+07:00",
        akadVenue: "Gedung Olah Raga Nasional Jakarta Barat",
        akadAddress: "Jl. Lorem Ipsum No 15",
        akadMapsUrl: "https://maps.google.com/maps?q=Rootpixel&t=&z=13&ie=UTF8&iwloc=&output=embed",
        receptionDatetime: "2026-12-23T19:00:00+07:00",
        receptionVenue: "Gedung Olah Raga Nasional Jakarta Barat",
        receptionAddress: "Jl. Lorem Ipsum No 15",
        receptionMapsUrl: "https://maps.google.com/maps?q=Rootpixel&t=&z=13&ie=UTF8&iwloc=&output=embed",
        groomPhoto: "/simple-forest/_assets/img/spouse/man.png",
        bridePhoto: "/simple-forest/_assets/img/spouse/woman.png",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya.",
        gallery: [
            "/simple-forest/_assets/img/gallery/1.jpg",
            "/simple-forest/_assets/img/gallery/2.jpg",
            "/simple-forest/_assets/img/gallery/3.jpg",
            "/simple-forest/_assets/img/gallery/4.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Hac nullam diam enim quis. Diam lorem est integer tellus scelerisque cursus nam donec." },
            { name: "Muh. Fahri Akbar", message: "Hac nullam diam enim quis. Diam lorem est integer tellus scelerisque cursus nam donec." },
            { name: "Yustisya", message: "Hac nullam diam enim quis. Diam lorem est integer tellus scelerisque cursus nam donec." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
    },
};
