/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * var2.js — Fallback data per template part 2
 * Used as the default when the API is unavailable.
 * The structure of each template may vary.
 */

var FALLBACK = {
    "smooth-snow": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        groomRole: "Putra dari",
        brideRole: "Putri dari",
        fatherGroom: "Bpk. Andi Idris & Ibu Sulaiman",
        fatherBride: "Bpk. Syam & Ibu Haeruddin",
        groomPhoto: "/smooth-snow/_assets/img/spouse/new/man.jpg",
        bridePhoto: "/smooth-snow/_assets/img/spouse/new/woman.jpg",
        backgroundCover: "/smooth-snow/_assets/img/misc/kiki-3.jpg",
        rsvpPhoto: "/smooth-snow/_assets/img/misc/kiki-2.jpg",
        galleryDesc: "Momen-momen indah yang kami abadikan bersama dalam perjalanan cinta kami.",
        akadDatetime: "2026-12-02T09:00:00+07:00",
        akadDesc: "Dengan penuh rasa syukur, kami mengundang Bapak/Ibu/Saudara/i untuk hadir.",
        akadVenue: "Gedung Serbaguna",
        akadAddress: "Jl. Lorem Ipsum X No. 123",
        akadMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        receptionDatetime: "2026-12-03T11:00:00+07:00",
        receptionDesc: "Dengan penuh rasa syukur, kami mengundang Bapak/Ibu/Saudara/i untuk hadir.",
        receptionVenue: "Gedung Serbaguna",
        receptionAddress: "Jl. Lorem Ipsum X No. 123",
        isShowGallery: true,
        isShowStory: true,
        gallery: [
            "/smooth-snow/_assets/img/gallery/1.jpg",
            "/smooth-snow/_assets/img/gallery/2.jpg",
            "/smooth-snow/_assets/img/gallery/3.jpg",
            "/smooth-snow/_assets/img/gallery/4.jpg",
            "/smooth-snow/_assets/img/gallery/5.jpg",
        ],
        storyItems: [
            { title: "Terlibat Suatu Project Bersama", description: "Pertemuan pertama yang tak terduga, dari sebuah project bersama, persahabatan kami perlahan tumbuh menjadi sesuatu yang lebih.", image: "/smooth-snow/_assets/img/misc/story-1.jpg" },
            { title: "Saling Mengenal Lebih Dalam", description: "Waktu demi waktu kami lalui bersama, saling mengenal satu sama lain dan menemukan kecocokan yang luar biasa.", image: "/smooth-snow/_assets/img/misc/story-2.jpg" },
            { title: "Memutuskan untuk Bersama", description: "Dengan penuh keyakinan dan rasa cinta, kami memutuskan untuk melangkah bersama menuju jenjang pernikahan.", image: "/smooth-snow/_assets/img/misc/story-3.jpg" },
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Selamat menempuh hidup baru, semoga menjadi keluarga yang sakinah mawaddah warahmah." },
            { name: "Muh. Fahri Akbar", message: "Barakallahu lakuma wa baraka alaikuma wa jama'a bainakuma fi khair." },
            { name: "Yustisya", message: "Semoga langgeng sampai kakek nenek dan selalu bahagia bersama." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        platform: "Our Platform",
        music: "/music.mp3",
    },

    "pink-brides": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika",
        brideName: "Putri",
        groomFullName: "Andika Ilyas, SE",
        brideFullName: "Putri Auliya, S.Pd",
        groomRole: "Putra dari",
        brideRole: "Putri dari",
        fatherGroom: "Bpk. Antonio & Ibu Christiani",
        fatherBride: "Bpk. Yuda Anggoro & Ibu Risa",
        groomPhoto: "/pink-brides/_assets/img/spouse/man.jpg",
        bridePhoto: "/pink-brides/_assets/img/spouse/woman.jpg",
        headerPhoto: "/pink-brides/_assets/img/misc/header-bridge.jpg",
        section1Quote: "\"Dua jiwa namun satu pikiran, dua hati namun satu perasaan\"",
        section3Title: "Akhir yang Indah",
        section3Desc: "Dengan penuh rasa syukur dan kebahagiaan, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu dalam pernikahan kami.",
        section3Quote: "\"Pernikahan dirancang oleh Alah agar manusia tidak sendirian, menjadikan mereka satu daging\"",
        section3QuoteSource: "Kejadian 2:18, 24",
        section3Photo: "/pink-brides/_assets/img/misc/lorem.jpg",
        storyPhoto1: "/pink-brides/_assets/img/misc/story-1.jpg",
        storyPhoto2: "/pink-brides/_assets/img/misc/story-2.jpg",
        storyTitle1: "Bagaimana Kami Bertemu",
        storyDesc1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Arcu quis et blandit urna neque pellentesque proin.",
        storyTitle2: "Saling Mengenal",
        storyDesc2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Arcu quis et blandit urna neque pellentesque proin.",
        schedulePhoto1: "/pink-brides/_assets/img/misc/schedule-1.jpg",
        schedulePhoto2: "/pink-brides/_assets/img/misc/schedule-2.jpg",
        schedulePhoto3: "/pink-brides/_assets/img/misc/schedule-1.jpg",
        akadDatetime: "2026-12-02T09:00:00+07:00",
        akadVenue: "Gedung Serbaguna",
        akadAddress: "Jl. Lorem Ipsum X No. 00",
        akadMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        receptionDatetime: "2026-12-05T11:00:00+07:00",
        receptionVenue: "Gedung Serbaguna",
        receptionAddress: "Jl. Lorem Ipsum X No. 00",
        receptionMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        gallery: [
            "/pink-brides/_assets/img/gallery/1.jpg",
            "/pink-brides/_assets/img/gallery/2.jpg",
            "/pink-brides/_assets/img/gallery/3.jpg",
            "/pink-brides/_assets/img/gallery/4.jpg",
            "/pink-brides/_assets/img/gallery/5.jpg",
            "/pink-brides/_assets/img/gallery/6.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Muh. Fahri Akbar", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Yustisya", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        platform: "Our Platform",
        music: "/music.mp3",
    },

    "elegant-classy": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika",
        brideName: "Putri",
        groomFullName: "Andika Ilyas, SE",
        brideFullName: "Putri Auliya, S.Pd",
        groomRole: "Putra dari",
        brideRole: "Putri dari",
        fatherGroom: "Bpk. Antonio & Ibu Christiani",
        fatherBride: "Bpk. Yuda Anggoro & Ibu Risa",
        groomPhoto: "/elegant-classy/_assets/img/spouse/man.png",
        bridePhoto: "/elegant-classy/_assets/img/spouse/woman.png",
        coverImage: "/elegant-classy/_assets/img/bg/header.jpg",
        backgroundSource: "/elegant-classy/_assets/img/bg/section-5.jpg",
        quote: "\"Dua jiwa namun satu pikiran, dua hati namun satu perasaan\"",
        section5Quote: "Pernikahan dirancang oleh Alah agar manusia tidak sendirian, menjadikan mereka satu daging",
        section5QuoteSource: "Kejadian 2:18, 24",
        akadDatetime: "2026-12-02T09:00:00+07:00",
        akadVenue: "Gedung Serbaguna",
        akadAddress: "Jl. Lorem Ipsum X No. 123",
        akadMapsUrl: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.7013734770944!2d119.5416101!3d-5.151678599999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee5f3a20f7aa3%3A0xc439ed1b0cd3f461!2sMulira.mks!5e0!3m2!1sid!2sid!4v1780652608210!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
        receptionDatetime: "2026-12-07T11:00:00+07:00",
        receptionVenue: "Gedung Serbaguna",
        receptionAddress: "Jl. Lorem Ipsum X No. 123",
        receptionMapsUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3973.430408191472!2d119.45920017579266!3d-5.1948336947827265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee35b6734a835%3A0x5fa0a6f1e5745ae8!2sPatung%20Massa!5e0!3m2!1sid!2sid!4v1775956244507!5m2!1sid!2sid",
        isShowGallery: true,
        isShowStory: true,
        gallery: [
            "/elegant-classy/_assets/img/gallery/1.jpg",
            "/elegant-classy/_assets/img/gallery/2.jpg",
            "/elegant-classy/_assets/img/gallery/3.jpg",
            "/elegant-classy/_assets/img/gallery/4.jpg",
            "/elegant-classy/_assets/img/gallery/1.jpg"
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Muh. Fahri Akbar", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
            { name: "Yustisya", message: "Adipiscing auctor amet vitae scelerisque sit augue euismod etiam cras. Eros at amet, mattis mi eget arcu sed." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
        storyItems: [
            { year: "2016", title: "Bagaimana Kami Bertemu", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies etiam malesuada vitae ipsum sed diam at.", image: "/elegant-classy/_assets/img/gallery/1.jpg" },
            { year: "2018", title: "Saling Mengenal", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies etiam malesuada vitae ipsum sed diam at.", image: "/elegant-classy/_assets/img/gallery/2.jpg" },
            { year: "2020", title: "Berkomitmen", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies etiam malesuada vitae ipsum sed diam at.", image: "/elegant-classy/_assets/img/gallery/3.jpg" },
            { year: "2022", title: "Lamaran & Nikah", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies etiam malesuada vitae ipsum sed diam at.", image: "/elegant-classy/_assets/img/gallery/4.jpg" },
        ],
        platform: "Our Platform"
    },

    "woods": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        eventDatetime: "2026-12-02T09:00:00+07:00",
        venue: "Jl. Lorem Ipsum X No. 123",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya.",
        couplePhoto: "/woods/_assets/img/spouse/man-woman.jpg",
        storyPhoto1: "/woods/_assets/img/misc/story-1.jpg",
        storyPhoto2: "/woods/_assets/img/misc/story-2.jpg",
        storyPhoto3: "/woods/_assets/img/misc/story-3.jpg",
        gallery: [
            "/woods/_assets/img/gallery/1.jpg",
            "/woods/_assets/img/gallery/2.jpg",
            "/woods/_assets/img/gallery/3.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Selamat menempuh hidup baru, semoga menjadi keluarga yang sakinah mawaddah warahmah." },
            { name: "Muh. Fahri Akbar", message: "Barakallahu lakuma wa baraka alaikuma wa jama'a bainakuma fi khair." },
            { name: "Yustisya", message: "Semoga langgeng sampai kakek nenek dan selalu bahagia bersama." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
    },

    "feminin": {
        guestName: "Bapak/Ibu/Saudara/i",
        groomName: "Andika Ilyas, SE",
        brideName: "Putri Auliya, S.Pd",
        eventDatetime: "2026-12-02T09:00:00+07:00",
        venue: "Jl. Lorem Ipsum X No. 123",
        quote: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya.",
        couplePhoto: "/feminin/_assets/img/spouse/man-woman.jpg",
        section1Photo: "/feminin/_assets/img/misc/section-1.jpg",
        gallery: [
            "/feminin/_assets/img/gallery/1.jpg",
            "/feminin/_assets/img/gallery/2.jpg",
            "/feminin/_assets/img/gallery/3.jpg",
            "/feminin/_assets/img/gallery/4.jpg",
            "/feminin/_assets/img/gallery/5.jpg",
            "/feminin/_assets/img/gallery/6.jpg",
        ],
        wishes: [
            { name: "Mumainnah Rusli", message: "Selamat menempuh hidup baru, semoga menjadi keluarga yang sakinah mawaddah warahmah." },
            { name: "Muh. Fahri Akbar", message: "Barakallahu lakuma wa baraka alaikuma wa jama'a bainakuma fi khair." },
            { name: "Yustisya", message: "Semoga langgeng sampai kakek nenek dan selalu bahagia bersama." },
        ],
        payment: [
            { name: "Andika Ilyas", method: "bca", value: "1234-5678" },
            { name: "Putri Auliya", method: "dana", value: "08123456789" },
        ],
        music: "/music.mp3",
    },
}